language: php
sudo: false

php:
 - 7.2

before_install:
  - rvm install 2.6
  - rvm use 2.6
  - gem install hiptest-publisher
  - "hiptest-publisher -c behat.conf --only=features,step_definitions --test-run-id=328969"
  - composer install

script:
  - php composer.phar install
  - vendor/bin/behat -f cucumber_json

after_script:
  - hiptest-publisher -c behat.conf --push=results/report.json --test-run-id=328969
