version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Install publisher and dependencies
          command: |
            make install_prerequisites
            sudo apt-get update
            sudo apt-get install ruby ruby-dev
            sudo gem install hiptest-publisher
      - run:
          name: Run tests
          command: |
            hiptest-publisher --config behat.conf \
              --token $SECRET_TOKEN \
              --test-run-id $TEST_RUN_ID \
              --without=actionwords
            vendor/bin/behat -f cucumber_json
      - run:
          name: Push results
          command: |
            hiptest-publisher --config behat.conf \
              --token $SECRET_TOKEN \
              --test-run-id $TEST_RUN_ID \
              --push=results/report.json \
              --execution-environment=CircleCI \
              --global-failure-on-missing-reports
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
