version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: make install_prerequisites
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: |
          make generate_tests_from_test_run
          make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
