version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: |
        make install_prerequisites
        sudo apt-get update
        sudo apt-get install ruby ruby-dev
        sudo gem install hiptest-publisher
      - run: |
        make generate_tests_from_test_run
        make test
      - run: |
        make push_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
